packages:
  - packages/*

allowBuilds:
  esbuild: true

catalogs:
  dev:
    '@antfu/eslint-config': ^5.0.0
    eslint: ^9.33.0
    tsdown: ^0.15.0
    typescript: ^5.9.2
    vitest: ^3.2.4
  dsh:
    '@deepseek-ai/cordis': ^4.0.2
    '@deepseek-ai/dsh-commands': ^0.1.1-rc.2
    '@deepseek-ai/dsh-sandbox-policy': ^0.1.1-rc.2
    '@deepseek-ai/dsh-settings': ^0.1.1-rc.2
    '@deepseek-ai/dsh-system-prompt': ^0.1.1-rc.2
    '@deepseek-ai/dsh-tools': ^0.1.1-rc.2
    '@deepseek-ai/dsh-workspace': ^0.1.1-rc.2

    '@deepseek-ai/schemastery': ^3.18.1
minimumReleaseAgeExclude:
  - '@deepseek-ai/cordis@4.0.2'
  - '@deepseek-ai/cosmokit@1.8.3'
